export function HomePage() {
  return (
    <div className="w-full flex flex-col items-center bg-red-500">
      새로운거
      <h1 className="text-4xl font-bold">Welcome to Wisoft Admin Dashboard</h1>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <h1 className="text-4xl font-bold">Welcome to Wisoft Admin Dashboard</h1>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <h1 className="text-4xl font-bold">Welcome to Wisoft Admin Dashboard</h1>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <h1 className="text-4xl font-bold">Welcome to Wisoft Admin Dashboard</h1>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <h1 className="text-4xl font-bold">Welcome to Wisoft Admin Dashboard</h1>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <h1 className="text-4xl font-bold">Welcome to Wisoft Admin Dashboard</h1>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
      <p className="text-lg">Select an item from the sidebar to navigate.</p>
    </div>
  );
}